version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: . 
    container_name: hapi-fhir-jpaserver-start 
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://hapi-fhir-postgres:5432/hapi    
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=dbuser
        - SPRING_JPA_HIBERNATE_DDL_AUTO=admin

    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    ports:
      - 5431:5431
volumes:
  hapi-fhir-postgres:
